config/routes.rb
ImageGallery::Application.routes.draw do

  resources :albums do
    resources :photos
  end

  devise_for :users

  root :to => 'albums#index'

  mount Blogit::Engine => "/blog"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  attr_accessible :blog_link, :caption, :description, :title

  validates_presence_of :title, :caption, :description

  acts_as_taggable
  has_many :comments, as: :commentable
  has_many :photos
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :email, :name

  belongs_to :commentable, polymorphic: true

  validates_presence_of :name, :email, :content
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
  attr_accessible :caption, :description, :image

  mount_uploader :image, ImageUploader

  #validates_presence_of :caption, :description, :image
  before_create :default_name

  def default_name
    self.caption ||= File.basename(image.filename, ".*").titleize if image
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :content

  belongs_to :taggable, polymorphic: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  blogs

  def admin?
    email == "admin@example.com"
  end
  
  def username
    email
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  check_authorization
  load_and_authorize_resource

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
  
  def login_required
    if !user_signed_in?
      redirect_to '/'
    end
  end
    
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  check_authorization
  load_and_authorize_resource :album
  load_and_authorize_resource :photo, through: :album
  #before_filter :initialize_album

  # GET /photos
  # GET /photos.json
  def index
    @photos = @album.photos

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create

    respond_to do |format|
      if @photo.save
        format.html { redirect_to [@album, @photo], notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: [@album, @photo] }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to [@album, @photo], notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to album_photos_url(@album) }
      format.json { head :no_content }
    end
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper  
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/albums/_form.html.slim
= form_for @album do |f|
  - if @album.errors.any?
    #error_explanation
      h2 = "#{pluralize(@album.errors.count, "error")} prohibited this album from being saved:"
      ul
        - @album.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description, :rows => '5'
  .field
    = f.label :caption
    = f.text_field :caption
  .field
    = f.label :blog_link
    = f.text_field :blog_link
  .actions = f.submit 'Save'

app/views/albums/edit.html.slim
h1 Editing album

== render 'form'

= link_to 'Show', @album
'|
= link_to 'Add Photos', new_album_photo_path(@album)
'|
= link_to 'Back', albums_path

app/views/albums/index.html.slim
- @albums.each do |album|
  .polaroid
    - if !album.photos.blank?
      = image_tag album.photos.first.image_url(:thumb), alt: album.title, data: { link: "#{album_url(album)}"}
    p= album.title
    p= link_to "View Album", album_photos_path(album)
    p= link_to "Edit Album", edit_album_path(album) if can? :edit, Album

br

= link_to 'New Album', new_album_path if can? :create, Album

app/views/albums/new.html.slim
h1 New album

== render 'form'

= link_to 'Back', albums_path

app/views/albums/show.html.slim
p#notice = notice

p
  strong Title:
  = @album.title
p
  strong Description:
  = @album.description
p
  strong Caption:
  = @album.caption
p
  strong Blog link:
  = @album.blog_link
p
  strong User:
  = @album.user

= link_to 'Edit', edit_album_path(@album)
'|
= link_to 'Add Photos', new_album_photo_path(@album)
'|
= link_to 'Back', albums_path

app/views/blogit/comments/_admin_links.html.erb
<%= login_required(class: "actions") do %>
  <%= link_to(t(:delete, scope: 'blogit.comments'), [@post, comment], method: :delete, confirm: t(:are_you_sure_you_want_to_remove_this_comment, scope: 'blogit.comments')) %>
<% end %>

app/views/blogit/comments/_comment.html.erb
<%= content_tag(:article, id: "blog_comment_#{comment.id}", class: "blog_comment") do %>
  <%= content_tag(:div, class: "blog_comment_name", id: "blog_comment_#{comment.id}_name") do %>
    <%= comment.website? ? link_to(comment.name, comment.website) : comment.name %>
    <%= t('blogit.comments.wrote') %>
  <% end %>


  <%= content_tag(:div, class: "blog_comment_body",
      id: "blog_comment_#{comment.id}_body") do %>
      <%= format_content comment.body || "" %>
  <% end %>

  <%= blog_tag(:footer, type: "comment") do %>
    <%=t :posted_on, scope: 'blogit.comments'%> 
    <%= time_tag(comment.created_at, format: blogit_conf.datetime_format) %>
  <% end %>

  <%= render partial: "blogit/comments/admin_links", locals: {comment: comment} %>

<% end if comment.persisted? %>

app/views/blogit/comments/_form.html.erb
<%= form_for [post, comment], remote: true,
  html: {
    class: "new_blog_comment bs-example", id: "new_blog_comment" } do |f| -%>

  <p><%=t :leave_a_comment, scope: 'blogit.comments'%></p>

  <%= field class: "hidden" do %>
    <%= f.label :nickname %>
    <%= f.text_field :nickname %>
    Hide me using CSS
  <% end %>

  <%= field class: "form-group" do %>
    <%= f.label :name, t(:name, scope: 'blogit.comments'), class: "control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <%= errors_on(comment, :name) %>
  <% end %>

  <%= field class: "form-group" do %>
    <%= f.label :email, t(:email_never_displayed, scope: 'blogit.comments'), class: "control-label" %>
    <div class="col-lg-10">
      <%= f.email_field :email, class: "form-control" %>
    </div>
    <%= errors_on(comment, :email) %>
  <% end %>

  <%= field class: "form-group" do %>
    <%= f.label :website, t(:your_website, scope: 'blogit.comments'), class: "control-label" %>
    <div class="col-lg-10">
      <%= f.url_field :website, class: "form-control" %>
    </div>
    <%= errors_on(comment, :website) %>
  <% end %>

  <%= field class: "form-group" do %>
    <%= f.label :body, t(:your_comment, scope: 'blogit.comments'), class: "control-label" %>
    <div class="col-lg-10">
      <%= f.text_area :body, class: "form-control" %><br>
    </div>
    <%= errors_on(comment, :body) %>
  <% end %>

  <%= field class: "form-group" do %>
  <div class="control-label"></div>
    <div class="col-lg-10">
      <%= actions do %>
        <%= f.submit t(:add_comment, scope: 'blogit.comments'), :disable_with => t(:adding_comment, scope: 'blogit.comments') %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/blogit/comments/create.js.erb
var $form = $("form#new_blog_comment");
<% if @comment.save %>
  $("#comments").append("<%= escape_javascript(render(@comment)) %>");
  $form.get(0).reset();
<% else %>
  $form.html("<%= escape_javascript(render('form', :comment => @comment, :post => @comment.post)) %>");
<% end %>

app/views/blogit/comments/destroy.js.erb
$("#comment_<%= @comment.id %>").remove();

app/views/blogit/posts/_active_record_comments.html.erb
<div id="comments">
  <%= render post.comments %>
</div>
<%= render partial: "blogit/comments/form", locals: { post: post, comment: comment } %>

app/views/blogit/posts/_blog_post_spacer.html.erb
<hr class="blog_post_spacer">

app/views/blogit/posts/_blogger_information.html.erb
<%= blog_tag :footer do %>
    <%=t :written_by, scope: 'blogit.posts', author: post.blogger_display_name %>
    <%= time_tag(post.created_at, pubdate: true, format: blogit_conf.datetime_format) %>
<% end %>

app/views/blogit/posts/_comments_count.html.erb
<%= content_tag(:div, class: "blog_post_comments_count", id: "blog_post_#{post.id}_comments_count") do %>
  <%= link_to(post_path(post, anchor: "comments")) do %>
    <%=t :comment, scope: 'blogit.posts', count: post.comments_count %>
  <% end %>
<% end %>

app/views/blogit/posts/_disqus_comments.html.erb
 <div id="disqus_thread"></div>
 <script type="text/javascript">
   /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
   var disqus_shortname = '<%= Blogit.configuration.disqus_shortname %>'; // required: replace example with your forum shortname

   /* * * DON'T EDIT BELOW THIS LINE * * */
   (function() {
     var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
     dsq.src = '<%= request.protocol %>' + disqus_shortname + '.disqus.com/embed.js?<%= request.protocol_name %>';
     (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
   })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/blogit/posts/_empty.html.erb
<div class="blogit_empty_message">
  <%=t :there_are_no_posts_about, scope: 'blogit.posts', tag: params[:tag] %>
</div>

app/views/blogit/posts/_form.html.erb
<%= form_for(@post, html: {class: "new_blog_post", id: "new_blog_post"}) do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%=t :prohibited_this_post_from_being_saved, scope: 'blogit.posts', count: @post.errors.count%></h2>

      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <%= field do %>
      <%= f.text_field :title, placeholder: t(:give_your_post_a_title, scope: 'blogit.posts'), class: "post_title" %>
    <% end %>

    <%= field do %>
      <%= f.text_area :body, placeholder: t(:write_something_here, scope: 'blogit.posts'), class: "post_textarea" %>
    <% end %>
  </fieldset>

  <fieldset>

    <%= field id: "new_blog_post_tag_field" do %>
      <%= f.label :tag_list, t(:tags, scope: 'blogit.posts') %>
      <%= f.text_field :tag_list, placeholder: t(:tag_placeholder, scope: 'blogit.posts'), class: "post_tags" %>
    <% end %>

    <p class="blog_post_tip">
      <%=t :tip_you_can_style_your_post_using, scope: 'blogit.posts', parser: blogit_conf.default_parser %>
    </p>

  </fieldset>

  <%= actions do %>
    <%= f.submit %> <%=t :or, scope: 'blogit.posts'%>
    <%= link_to(t(:cancel, scope: 'blogit.posts'), @post.new_record? ? blog_root_path : post_path(@post)) %>
  <% end %>

<% end %>

app/views/blogit/posts/_pagination.html.erb
<%= paginate(@posts) %>

app/views/blogit/posts/_post.html.erb
<%= content_tag(:article, id: "blog_post_#{post.id}", class: "blog_post") do %>

  <%# Render the header for this blog post %>
  <%= render "blogit/posts/post_head", post: post %>

  <%# Render info about the person who wrote this post %>
  <%= render "blogit/posts/blogger_information", post: post %>

  <div class="post-content">
  <%# Render the body of this blog post (as Markdown) %>
  <%= render "blogit/posts/post_body", post: post %>
  
  <div class="readmorecontent">
  <%= link_to "Read More", post, class: "readmore"%>
  </div>
  </div>

  <%# Render admin links to edit/delete this post %>
  <%= render "blogit/posts/post_links", post: post %>

  <%# Render the no. of comments %>
  <%= render "blogit/posts/comments_count",
    post: post if defined?(show_comments_count) and show_comments_count %>

<% end %>

app/views/blogit/posts/_post_links.html.erb
<%= login_required do  %>
  <%= actions do %>
    <%= link_to(t(:edit, scope: 'blogit.posts'), edit_post_path(post)) %> | <%= link_to(t(:delete, scope: 'blogit.posts'), post, method: :delete, confirm: t(:are_you_sure_you_want_to_remove_this_post, scope: 'blogit.posts')) %>
  <% end %>
<% end unless blogit_conf.author_edits_only and not this_blogger?(post) %>

app/views/blogit/posts/_share_bar.html.erb
<div id="blog_share_bar">

  <div id="google-plus" class="social_button">
    <!-- GOOGLE +1 -->
    <g:plusone size="medium"></g:plusone>
    <script type="text/javascript">
      window.___gcfg = {lang: '<%= I18n.default_locale %>'};

      (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();
    </script>
    <!-- /GOOGLE +1 -->
  </div>

  <div id="twitter" class="social_button">
    <!-- TWITTER -->
    <a href="https://twitter.com/share" class="twitter-share-button"
        data-lang="<%= I18n.default_locale %>"
        data-url="http://<%= request.host_with_port %><%= request.path.gsub("//","/") %>"
        data-via="<%= Blogit.configuration.twitter_username %>"
        data-text="<%= post.title%>"
        data-count="horizontal">Tweet</a>

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <!-- /TWITTER -->
  </div>

  <div id="facebook" class="social_button">
    <!-- FACEBOOK LIKE -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/<%= t "blogit.share_bar.facebook" %>/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <div class="fb-like" data-send="false"  data-layout="button_count" data-width="90" data-show-faces="false"></div>
    <!-- /FACEBOOK LIKE -->
  </div>

</div>

app/views/blogit/posts/edit.html.erb
<h2><%=t :edit_blog_post, scope: 'blogit.posts', id: @post.id %></h2>

<%= render 'form' %>

app/views/blogit/posts/new.html.erb
<h2><%=t :write_a_new_blog_post, scope: 'blogit.posts'%></h2>

<%= render 'form' %>

app/views/blogit/posts/show.html.erb
<%= render @post %>
<%= share_bar_for @post %>
<%= render "blogit/posts/post_footer", post: @post %>
<%= comments_for @post %>

app/views/layouts/albums.html.slim
doctype 5
html
  head
    title Photo Gallery 
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "/js/jquery.polaroid.js"
    = csrf_meta_tags
  body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          a.brand href="#{root_url}" Photo Gallery 
          .nav-collapse.collapse.navbar-responsive-collapse
            ul.nav
              li.active
                a Home
              li
                a href="#" About Me
            ul.nav.pull-right
              - if user_signed_in? && current_user.admin?
                li
                  a href="#"
                    = current_user.email
                li.divider-vertical
                li= link_to "Sign out", destroy_user_session_url, :method => :delete
              /- else
                li= link_to "Sign In", new_user_session_url

    .container
      - if notice
        p.notice.alert
          = notice
      - if alert
        p.alert.alert-error
          = alert
      = yield

app/views/layouts/application.html.slim
doctype 5
html
  head
    title Photo Gallery 
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body.blog
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          a.brand href="/" Photo Gallery 
          .nav-collapse.collapse.navbar-responsive-collapse
            ul.nav
              li.active
                a Home
              li
                a href="#" About Me
            /ul.nav.pull-right
              - if user_signed_in?
                li
                  a href="#"
                    = current_user.email
                li.divider-vertical
                li= link_to "Sign out", destroy_user_session_url, :method => :delete
              - else
                li= link_to "Sign In", new_user_session_url

    .container
      - if notice
        p.notice.alert
          = notice
      - if alert
        p.alert.alert-error
          = alert
      = yield

app/views/layouts/photos.html.slim
doctype 5
html
  head
    title Photo Gallery 
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag "/css/demo.css", :media => "all"
    = stylesheet_link_tag "/css/jquery.lightbox-0.5.css", :media => "all"
    = stylesheet_link_tag "/css/jquery-tilesgallery.css", :media => "all"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "/js/jquery-1.7.1.min.js"
    = javascript_include_tag "/js/jquery.lightbox-0.5.pack.js"
    = javascript_include_tag "/js/jquery.tilesgallery.js"
    = csrf_meta_tags
  body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          a.brand href="#{root_url}" Photo Gallery 
          .nav-collapse.collapse.navbar-responsive-collapse
            ul.nav
              li.active
                a Home
              li
                a href="#" About Me
            /ul.nav.pull-right
              - if user_signed_in?
                li
                  a href="#"
                    = current_user.email
                li.divider-vertical
                li= link_to "Sign out", destroy_user_session_url, :method => :delete
              - else
                li= link_to "Sign In", new_user_session_url

    .container
      - if notice
        p.notice.alert
          = notice
      - if alert
        p.alert.alert-error
          = alert
      = yield

app/views/photos/_form.html.slim
h2
  = @album.title

= form_for [@album, @photo] do |f|
  - if @photo.errors.any?
    #error_explanation
      h2 = "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:"
      ul
        - @photo.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :caption
    = f.text_field :caption
  .field
    = f.label :description
    = f.text_area :description, :rows => "4"
  .field
    = f.file_field :image
  .actions = f.submit 'Save'

app/views/photos/create.js.slim
- if @painting.new_record?
  alert("Failed to upload painting: <%= j @painting.errors.full_messages.join(', ').html_safe %>");
- else
  $("#paintings").append("<%= j render(@painting) %>");

app/views/photos/edit.html.slim
h1 Editing photo

== render 'form'

= link_to 'Show', [@album, @photo]
'|
= link_to 'Back', album_photos_path(@album)

app/views/photos/index.html.slim
.tiles
  - @photos.each do |photo|
    a[href=photo.image_url(:display)]
      = image_tag photo.image_url(:display), :alt => photo.caption
    /tr
      td = photo.caption
      td = photo.description
      td = image_tag photo.image_url(:display)
      td = photo.album.title
      td = link_to 'Show', [@album, photo]
      td = link_to 'Edit', edit_album_photo_path(@album, photo)
      td = link_to 'Destroy', [@album, photo], :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Photo', new_album_photo_path(@album) if can? :create, Album

app/views/photos/new.html.slim
h1 Add photos

= form_for [@album, @photo] do |f|
  = f.label :image, "Upload paintings:"
  = f.file_field :image, multiple: true, name: "photo[image]"
  = f.submit 'Upload Photo'

script id="template-upload" type="text/x-tmpl"
  .upload
    /{%=o.name%}
    .progress
      .bar style="width: 0%"


= link_to 'Back', album_photos_path(@album)

app/views/photos/show.html.slim
p#notice = notice

p
  strong Caption:
  = @photo.caption
p
  strong Description:
  = @photo.description
p
  strong Image:
  = @photo.image
p
  strong Album:
  = @photo.album

= link_to 'Edit', edit_album_photo_path(@photo)
'|
= link_to 'Back', album_photos_path(@album)